Feature/main
wedaa-tech/wda-ui pull request #16
Opened 2023-10-06 06:56 UTC by raxkumar-wedaa

- limit project name size

- description size - 120, default text: No description available.

- correct project name in architectures page

- responsive tiles

- selectable texts

- remove draft counts

- remove authentication for canvas to code

- Update navbar

2023-10-10 16:03 UTC, raxkumar-wedaa commented on src/pages/Designer.js
> +        console.log(Data)
remove console log

2023-10-10 16:03 UTC, raxkumar-wedaa commented on src/pages/Designer.js
> +        console.log(nodeClick, UpdatedNodes);
remove console log

2023-10-10 16:36 UTC, rohith-wedaa requested changes

2023-10-10 16:36 UTC, rohith-wedaa commented on src/components/DownloadButton.js
> +            Export to PNG
Label could be - **Save as Image**

2023-10-10 16:36 UTC, rohith-wedaa commented on src/pages/Designer.js
> +        console.log(color);
remove console log

2023-10-10 16:36 UTC, rohith-wedaa commented on src/pages/Rewiew/CodeReview.js
> +            </Button> */}
No commented code

2023-10-10 16:36 UTC, rohith-wedaa commented on src/pages/Rewiew/Infrastructure.js
Since Infrastructure is moved to Review component, the original one can be removed.

2023-10-14 15:08 UTC, raxkumar-wedaa reviewed
Please resolve the comments if anything is pending #Dheeraj

Merging for now

2023-10-14 15:09 UTC, merged