Feature/UI gateway seperation(#KHarsha)
wedaa-tech/wda-ui pull request #2
Opened 2023-09-06 10:25 UTC by raxkumar-wedaa

- Created a Gateway Modal 
- Modified UI modal with application name and port number check 
- Connection between UI to Service,UI to Gateway and Gateway to Service is set by default rest
- No connection from other node to UI and UI to Db

2023-09-06 11:15 UTC, craxkumar requested changes

2023-09-06 11:15 UTC, craxkumar commented on src/components/Modal/GatewayModal.js
> +    if (column === "serverPort" && ApplicationData.serverPort === "9000") {
No need of the default value

2023-09-06 11:15 UTC, craxkumar commented on src/components/Modal/GatewayModal.js
> +                Port Number already exists. Please choose a unique Number.
unique port or unique port number.
but not 
unique number.

2023-09-06 12:17 UTC, raxkumar-wedaa reviewed
Please resolve !

2023-09-06 12:17 UTC, raxkumar-wedaa commented on src/components/Modal/GatewayModal.js
> +  const ValidatePortNumber = (value) => {
method/function names should be camel casing always 
validatePortNumber !!

2023-09-08 04:15 UTC, rohith-wedaa approved these changes

2023-09-08 04:15 UTC, merged